export const ACTION_LIKE = 'ACTION_LIKE';
export const ACTION_REMOVE = 'ACTION_REMOVE';
export const ACTION_ADD = 'ACTION_ADD';

export const MAIN_COMMENT_LIKE = 'MAIN_COMMENT_LIKE';
export const MAIN_COMMENT_REMOVE = 'MAIN_COMMENT_REMOVE';
export const MAIN_COMMENT_ADD = 'MAIN_COMMENT_ADD';

export const SUB_COMMENT_LIKE = 'SUB_COMMENT_LIKE';
export const SUB_COMMENT_REMOVE = 'SUB_COMMENT_REMOVE';

export const ADD_VIDEO = 'ADD_VIDEO';